version: '3.3'

services:

  app:
    image: secret-crush
    environment:
      - SERVER_PORT=80
    ports:
      - 3000:80

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  db-admin:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=db
    ports:
      - 8081:8081

volumes:
  mongo:
