export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const NO_SUCH_USER = 'NO_SUCH_USER'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const NEW_CRUSH = 'NEW_CRUSH'
export const NEW_MATCH = 'NEW_MATCH'
export const NEW_USER = 'NEW_USER'
